version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mood-holic
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 마운트
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3100:3000"  # Grafana의 포트를 3100으로 변경
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 관리자 비밀번호
    networks:
      - my_network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mariadb_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  my_network:
