version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mood-holic
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

volumes:
  mariadb_data:
  redis_data:

networks:
  my_network:
